# DO NOT EDIT THIS FILE
# this function is called at each tick of the game
# it protects the real on_tick function from being called if the game is over
execute if score game_state game_score matches 0 run function custom:on_tick
