# DO NOT EDIT THIS FILE
# this function is called when a game ending condition is met
# it is used to prevent the real end_challenge function from being called if the game is over
execute if score game_state game_score matches 0 run function custom:end_challenge
